CREATE TABLE IF NOT EXISTS match_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    demand_id BIGINT NOT NULL,
    current_tier INT NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'MATCHING',
    fail_reason VARCHAR(100) NULL,
    success_owner_id BIGINT NULL,
    success_service_item_id BIGINT NULL,
    ended_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE match_attempt
    ADD COLUMN task_id BIGINT NULL,
    ADD COLUMN tier_no INT NULL,
    ADD COLUMN distance_meter INT NULL,
    ADD COLUMN owner_response_deadline DATETIME NULL,
    ADD COLUMN farmer_confirm_deadline DATETIME NULL,
    ADD COLUMN close_reason VARCHAR(50) NULL,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE contact_session
    ADD COLUMN service_item_id BIGINT NULL,
    ADD COLUMN contact_mode VARCHAR(20) NULL,
    ADD COLUMN expire_at DATETIME NULL,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
